
DROP TABLE IF EXISTS 'reservation';
DROP TABLE IF EXISTS 'users';
DROP TABLE IF EXISTS 'packages';
CREATE TABLE "reservation" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fullname VARCHAR NOT NULL,
	address VARCHAR NOT NULL,
	contact INTEGER NOT NULL,
	emailaddress VARCHAR NOT NULL,
	age INTEGER NOT NULL,
	sex VARCHAR NOT NULL,
	category VARCHAR NOT NULL,
	date VARCHAR NOT NULL,
	time VARCHAR NOT NULL,
	package VARCHAR NOT NULL,
	status VARCHAR
);

CREATE TABLE "users" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fullname VARCHAR NOT NULL,
	username VARCHAR NOT NULL,
	password VARCHAR NOT NULL
);

CREATE TABLE "packages" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	packagename VARCHAR NOT NULL,
	description VARCHAR NOT NULL,
	price DECIMAL NOT NULL,
	person VARCHAR NOT NULL,
	food VARCHAR NOT NULL,
	img VARCHAR
);


