
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS packages;
CREATE TABLE "reservation" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fullname TEXT NOT NULL,
	address TEXT NOT NULL,
	contact TEXT NOT NULL,
	emailaddress TEXT NOT NULL,
	category TEXT NOT NULL,
	date TEXT NOT NULL,
	time TEXT NOT NULL,
	package TEXT NOT NULL,
	status TEXT
);

CREATE TABLE "users" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	fullname TEXT NOT NULL,
	username TEXT NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE "packages" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	packagename TEXT NOT NULL,
	description TEXT NOT NULL
	
);


